title: "Guidelines for Drafting Manuscripts"
author: Pawel Kaminski
copyright: "2025"
# logo: logo.png

repository:
  url: https://github.com/monograph-prototypes/guidelines-for-drafting-manuscripts
html:
  use_repository_button: true
  use_issues_button: true

execute:
  execute_notebooks: 'off'
